services:

  postgres:
    image: postgres:15
    container_name: book-store
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: khang
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: store
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: book-store-redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: 123456
      REDIS_HOST: localhost
    command: redis-server --requirepass 123456
    volumes:
      - redis_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    container_name: book-store-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "9000:8080"
    depends_on:
      - postgres

volumes:
  postgres-data:
  redis_data: